name: vit-centerline
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - expat=2.7.4
  - ld_impl_linux-64=2.44
  - libexpat=2.7.4
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libnsl=2.0.0
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.0.19
  - packaging=25.0
  - pip=25.3
  - pthread-stubs=0.3
  - python=3.11.14
  - readline=8.3
  - setuptools=80.10.2
  - sqlite=3.51.1
  - tk=8.6.15
  - tzdata=2025c
  - wheel=0.46.3
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.12.1
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - click==8.3.1
      - fastapi==0.128.0
      - filelock==3.20.0
      - fsspec==2025.12.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.3.7
      - idna==3.11
      - jinja2==3.1.6
      - joblib==1.5.3
      - markupsafe==2.1.5
      - mpmath==1.3.0
      - networkx==3.6.1
      - numpy==2.3.5
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.1.105
      - pandas==3.0.0
      - pillow==12.0.0
      - psycopg2-binary==2.9.11
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - pyyaml==6.0.3
      - requests==2.32.5
      - safetensors==0.7.0
      - scikit-learn==1.8.0
      - scipy==1.17.0
      - shellingham==1.5.4
      - six==1.17.0
      - starlette==0.50.0
      - sympy==1.13.1
      - threadpoolctl==3.6.0
      - timm==1.0.24
      - torch==2.5.1+cu121
      - torchvision==0.20.1+cu121
      - tqdm==4.67.3
      - triton==3.1.0
      - typer-slim==0.21.1
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - urllib3==2.6.3
      - uvicorn==0.40.0
prefix: /home/ubuntu/anaconda3/envs/vit-centerline
